---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  labels:
    {{- include "modern-gitops-stack-module-kafka.labels" $ | indent 4 }}
  {{- if .Values.kafka.kraft }}
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  {{- end }}
spec:
  kafka:
    template:
        persistentVolumeClaim:
          metadata:
            annotations:
              argocd.argoproj.io/compare-options: IgnoreExtraneous
              argocd.argoproj.io/sync-options: Prune=false
    version: {{ .Values.kafka.version }}
    metadataVersion: {{ .Values.kafka.versionProtocol }}-IV0
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    config:
    # Report and UI for Cruise Control
      metric.reporters: "com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter"
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: {{ .Values.kafka.replicas }}
      transaction.state.log.replication.factor: {{ .Values.kafka.replicas }}
      transaction.state.log.min.isr: 2
      default.replication.factor: {{ .Values.kafka.replicas }}
      min.insync.replicas: 2
      unclean.leader.election.enable: "false"
      {{- if not .Values.kafka.kraft }}
      log.message.format.version: {{ .Values.kafka.versionProtocol }}
      inter.broker.protocol.version: {{ .Values.kafka.versionProtocol }}
      {{- end }}
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.storage.size }}
        deleteClaim: false
    resources:
      requests:
        memory: {{ .Values.kafka.resources.kafka.requests.memory }}
        cpu: {{ .Values.kafka.resources.kafka.requests.cpu }}
      limits:
        memory: {{ .Values.kafka.resources.kafka.limits.memory }}
        cpu: {{ .Values.kafka.resources.kafka.limits.cpu }}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: {{ .Values.kafka.name }}-kafka-metrics
          key: kafka-metrics-config.yml
  {{- if not .Values.kafka.kraft }}
  zookeeper:
    template:
        persistentVolumeClaim:
          metadata:
            annotations:
              argocd.argoproj.io/compare-options: IgnoreExtraneous
              argocd.argoproj.io/sync-options: Prune=False
    replicas: {{ .Values.kafka.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.storage.size }}
      deleteClaim: false
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    resources:
      requests:
        memory: {{ .Values.kafka.resources.zookeeper.requests.memory }}
        cpu: {{ .Values.kafka.resources.zookeeper.requests.cpu }}
      limits:
        memory: {{ .Values.kafka.resources.zookeeper.limits.memory }}
        cpu: {{ .Values.kafka.resources.zookeeper.limits.cpu }}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: {{ .Values.kafka.name }}-zookeeper-metrics
          key: zookeeper-metrics-config.yml
  {{- end }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
  cruiseControl:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: {{ .Values.kafka.name }}-cruise-control-metrics
          key: metrics-config.yml
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
